### PR TITLE
Fix #16 Property `new T Foo {get; set;}` setters are modified incorrectly.

### LINKED ISSUE #16: Virtualizing Hidden (`new`) Property Implementation breaks External Callers
Given the following code:

    public abstract class BaseProperty
    {
        public Object Value { get; set; }
    }

    public class GenericProperty<T> : BaseProperty
    {
        public new T Value
        {
            get => (T) base.Value;
            set => base.Value = value;
        }
    }

When I have a caller in another assembly:

    class Program
    {
        static void Main(string[] args)
        {
            var gp = new GenericProperty<DateTimeOffset>();

            Console.WriteLine(gp.Value.ToLocalTime());
        }
    }

I get a build error (only visible on the console! VS does not show an issue):

> C:\work\VirtuosityNewOverridePropertyIssue\Externalusage\Program.cs(12,40,12,51):
 error CS1061: 'object' does not contain a definition for 'ToLocalTime' and no extension method 'ToLocalTime' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)

A caller in the same assembly as where the Property is defined, however, will work just fine.

Issue exists with both 1.20.0 and my recent changes in 1.20.1

Here is a repro: 
[VirtuosityNewOverridePropertyIssue.zip](https://github.com/Fody/Virtuosity/files/1333248/VirtuosityNewOverridePropertyIssue.zip)

Note: I'm not the author of the code. I'm currently investigating how to fix this.

### PR DESCRIPTION
**Pull request by BrunoJuchli**
The issue reported in #16 was caused by `ModuleWeaver.ConvertNewToOverrides` (NewToOverideConverter.cs) removing `NewSlot` from the setter's method definition - this because it considered the setter to have a matching base method, as a same-assembly base-class with a "matching" method signature was detected.
The match was detected by comparing:
- method name
- method return type

I've changed this to also include all method parameters:
- same count
- same types
- same sequence

I've added unit tests for this specific case to uncover incorrectly removed `NewSlot` flags and others for code that works in an unexpected way.

I've also bumped the version from 1.20.1 to 1.20.2

Note: I believe my change should not break any currently working scenarios but possiby there's other scenarios which have not been fixed yet (that haven't worked before, either). 
Maybe a change of the sequence in `ModuleWeaver.Execute()` or actually tracking which methods potentially need `NewSlot` removed (if possible?) would further improve Virtuosity.

### CODE REVIEW

**Comment by BrunoJuchli** [comment]
Sorry, I'm not that well versed with GIT/Github and in order to have the new codebase for the fix for #18 I have put this in the same PR.

**Comment by SimonCropp** [comment]
gave u commit rights. what is your nuget handle and i will add u there

**Comment by BrunoJuchli** [comment]
Thank you, Simon.
I don't really know what the nuget handle is, but I use my e-mail address bruno.juchli@innocreative.ch to sign-in on nuget and my profile page id on nuget is [BrunoJuchli](https://www.nuget.org/profiles/BrunoJuchli). 
I guess it must be either of these, as the API keys should be kept a secret :D

**Comment by BrunoJuchli** [comment]
@SimonCropp 
Thanks for adding me to the Fody Org. Sorry, I was a bit stupid... I forgot to check my private e-mail and so I didn't see the invitation and assumed the assignation hadn't been carried out.

Nuget: bruno.juchli@innocreative.ch to sign-in on nuget and my profile page id on nuget is [BrunoJuchli](https://www.nuget.org/profiles/BrunoJuchli).

**Comment by SimonCropp** [comment]
u should have a nuget invite

**Comment by SimonCropp** [comment]
and i added u to appveyor

**Pull request merged**
